repos:
- repo: https://github.com/python/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-bugbear==20.1.4"]
